name: Refresh image URL

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure GitHub authentication
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Generate new version value
        id: version
        run: echo "ver=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Replace version in README
        run: |
          sed -i "s|v=[0-9]*|v=${{ steps.version.outputs.ver }}|g" README.md

      - name: Commit changes
        run: |
          git commit -am "Auto-bump cache version" || echo "No changes"
          git push
